<?php

define("DATABASE_NAME", trim($_ENV["HA_APP_ENV"]) === "DEV" ? trim($_ENV["DEVELOPMENT_DATABASE"]) : trim($_ENV["PRODUCTION_DATABASE"]));
define("DATABASE_USERNAME", trim($_ENV["HA_APP_ENV"]) === "DEV" ? trim($_ENV["DEVELOPMENT_DATABASE_USER"]) : trim($_ENV["PRODUCTION_DATABASE_USER"]));
define("DATABASE_PASSWORD", trim($_ENV["HA_APP_ENV"]) === "DEV" ? trim($_ENV["DEVELOPMENT_DATABASE_PASSWORD"]) : trim($_ENV["PRODUCTION_DATABASE_PASSWORD"]));
define("DATABASE_PORT", trim($_ENV["HA_APP_ENV"]) === "DEV" ? trim($_ENV["DEVELOPMENT_DATABASE_PORT"]) : trim($_ENV["PRODUCTION_DATABASE_PORT"]));
define("DATABASE_HOST", trim($_ENV["HA_APP_ENV"]) === "DEV" ? trim($_ENV["DEVELOPMENT_DATABASE_HOST"]) : trim($_ENV["PRODUCTION_DATABASE_HOST"]));
