<html>
<head>
<title>HA_MarketPlace_API REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>HA_MarketPlace_API REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Admin_Notifications</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_admin_notifications/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_admin_notifications/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_admin_notifications/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_admin_notifications/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_admin_notifications/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Admin_Password_Resets</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_admin_password_resets/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_admin_password_resets/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_admin_password_resets/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_admin_password_resets/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_admin_password_resets/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Admins</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_admins/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_admins/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_admins/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_admins/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_admins/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Agent_Logins</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_agent_logins/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_agent_logins/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_agent_logins/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_agent_logins/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_agent_logins/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Agents</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_agents/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_agents/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_agents/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_agents/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_agents/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Agents_Password_Resets</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_agents_password_resets/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_agents_password_resets/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_agents_password_resets/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_agents_password_resets/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_agents_password_resets/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Applied_Coupons</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_applied_coupons/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_applied_coupons/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_applied_coupons/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_applied_coupons/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_applied_coupons/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Brands</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_brands/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_brands/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_brands/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_brands/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_brands/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Carts</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_carts/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_carts/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_carts/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_carts/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_carts/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Categories</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_categories/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_categories/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_categories/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_categories/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_categories/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Coupons</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_coupons/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_coupons/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_coupons/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_coupons/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_coupons/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Coupons_Categories</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_coupons_categories/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_coupons_categories/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_coupons_categories/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_coupons_categories/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_coupons_categories/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Coupons_Products</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_coupons_products/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_coupons_products/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_coupons_products/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_coupons_products/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_coupons_products/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Email_Logs</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_email_logs/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_email_logs/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_email_logs/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_email_logs/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_email_logs/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Email_Sms_Templates</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_email_sms_templates/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_email_sms_templates/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_email_sms_templates/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_email_sms_templates/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_email_sms_templates/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Gateway_Currencies</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_gateway_currencies/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_gateway_currencies/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_gateway_currencies/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_gateway_currencies/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_gateway_currencies/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Gateways</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_gateways/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_gateways/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_gateways/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_gateways/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_gateways/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_General_Settings</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_general_settings/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_general_settings/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_general_settings/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_general_settings/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_general_settings/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Kyc_Documents</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_kyc_documents/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_kyc_documents/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_kyc_documents/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_kyc_documents/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_kyc_documents/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Kycs</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_kycs/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_kycs/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_kycs/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_kycs/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_kycs/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Languages</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_languages/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_languages/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_languages/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_languages/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_languages/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Messages</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_messages/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_messages/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_messages/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_messages/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_messages/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Offers</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_offers/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_offers/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_offers/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_offers/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_offers/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Offers_Products</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_offers_products/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_offers_products/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_offers_products/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_offers_products/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_offers_products/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Order_Details</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_order_details/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_order_details/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_order_details/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_order_details/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_order_details/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Orders</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_orders/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_orders/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_orders/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_orders/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_orders/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Password_Resets</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_password_resets/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_password_resets/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_password_resets/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_password_resets/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_password_resets/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Product_Reviews</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_product_reviews/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_product_reviews/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_product_reviews/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_product_reviews/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_product_reviews/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Properties</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_properties/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_properties/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_properties/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_properties/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_properties/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Sell_Logs</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_sell_logs/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_sell_logs/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_sell_logs/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_sell_logs/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_sell_logs/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Shops</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_shops/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_shops/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_shops/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_shops/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_shops/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Stock_Logs</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_stock_logs/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_stock_logs/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_stock_logs/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_stock_logs/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_stock_logs/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Subscribers</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_subscribers/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_subscribers/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_subscribers/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_subscribers/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_subscribers/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Support_Attachments</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_support_attachments/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_support_attachments/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_support_attachments/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_support_attachments/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_support_attachments/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Support_Messages</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_support_messages/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_support_messages/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_support_messages/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_support_messages/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_support_messages/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Support_Tickets</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_support_tickets/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_support_tickets/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_support_tickets/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_support_tickets/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_support_tickets/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Transactions</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_transactions/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_transactions/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_transactions/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_transactions/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_transactions/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_User_Logins</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_user_logins/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_user_logins/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_user_logins/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_user_logins/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_user_logins/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Users</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_users/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_users/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_users/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_users/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_users/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Wallet</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_wallet/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_wallet/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_wallet/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_wallet/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_wallet/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Wallet_Deposits</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_wallet_deposits/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_wallet_deposits/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_wallet_deposits/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_wallet_deposits/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_wallet_deposits/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Wishlists</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_wishlists/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_wishlists/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_wishlists/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_wishlists/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_wishlists/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Withdraw_Methods</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_withdraw_methods/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_withdraw_methods/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_withdraw_methods/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_withdraw_methods/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_withdraw_methods/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ha_Withdrawals</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ha_withdrawals/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ha_withdrawals/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ha_withdrawals/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ha_withdrawals/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ha_withdrawals/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
